### PR TITLE
Fix brew audit warnings and cli build failure

### PR DESCRIPTION
**Pull request by scribblemaniac**
This PR was initially just to fix the warnings produced by `brew audit --strict gridcoin`. As I went through them, I ended up doing multiple other little things here and there. In the end, this PR does the following:
- Fix all brew audit warnings. These are all just stylistic changes to match core Homebrew formulae.
- Fix cli build failure. The install block for --with-cli does some weird and unnecessary things, and references the makefile.osx which as far as I can tell was removed a long time ago. It works now though.
- Add --without-qrencode flag. This was an option built into gridcoin so we might as well have a flag for it.
- Add implementation for test block. Just gets the version or help menu to see if the executables work.
- Run unit tests when installing. Many core Homebrew formulae seem to do this, and the Gridcoin docs recommend it as well.
- Disable built-in upgrader. Currently this does nothing because the built-in upgrader was removed from the client, but add it anyway for when/if it is added back. This would be desireable since brew upgrade already handles upgrading.

### CODE REVIEW

**Comment by Git-Jiro** [comment]
Hi!
Before I merge this, can you remove the License stanza again?
It seems to break the macOS 10.3 compatible build in Travis CI.

**Comment by scribblemaniac** [comment]
Let me look into this. I have 10.13 and the formula installs just fine on it.

**Comment by Git-Jiro** [comment]
Ok interesting. Then most probably the Homebrew version in the Travis CI image is outdated.

**Comment by scribblemaniac** [comment]
Yes Travis almost never seems to update their images. I assumed it wouldn't be a problem because Homebrew usually automatically runs brew update before starting many commands, but Travis also explicitly disabled that: https://travis-ci.org/github/Git-Jiro/homebrew-jiro/builds/742337948#L60. I've added a call to brew update and it's working now. This is probably a good idea to do anyway to make sure the dependencies are all up to date. I also had to separate the dependency installation into a different step since that adds just enough time for travis_wait to time out.

**Pull request merged**
